#
# Â© 2026-present https://github.com/cengiz-pz
#

[versions]
compileSdk = "35"
minSdk = "24"
buildTools = "35.0.0"
appcompat = "1.7.1"
mlkit-barcode-scanning = "18.3.1"
zxing = "3.5.4"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
mlkit-barcode-scanning = { group = "com.google.android.gms", name = "play-services-mlkit-barcode-scanning", version.ref = "mlkit-barcode-scanning" }
zxing-core = { module = "com.google.zxing:core", version.ref = "zxing" }

[plugins]
android-library = { id = "com.android.library", version = "8.6.1" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "2.2.0" }
undercouch-download = { id = "de.undercouch.download", version = "5.6.0" }
